{application,herp,
             [{description,"HPCloud bindings"},
              {vsn,"1"},
              {registered,[]},
              {applications,[asn1,observer,wx,crypto,inets,kernel,public_key,
                             runtime_tools,ssl,stdlib]},
              {mod,{herp_app,[]}},
              {env,[]},
              {modules,[herp_app,herp_client,herp_client_sup,herp_identity,
                        herp_object,herp_refreg,herp_refreg_sup,herp_sup]}]}.
